@startuml

!include ../entities/EthernetSwitch.puml
!include GormGenericRepository.puml

package infrastructure {
    class EthernetSwitchRepository

    EthernetSwitchRepository -down-* GormGenericRepository


    note "EntityType is EthernetSwitch" as EthernetSwitchTypeNote

    EthernetSwitchRepository .down. EthernetSwitchTypeNote
    GormGenericRepository <.up. EthernetSwitchTypeNote
    EthernetSwitch .. EthernetSwitchTypeNote
}

@enduml
