@startuml

!include ../entities/EthernetSwitch.puml
!include GormGenericRepository.puml

package infrastructure {
    class GormEthernetSwitchRepository

    GormEthernetSwitchRepository -down-* GormGenericRepository


    note "EntityType is EthernetSwitch \nIDType is uuid.UUID" as EthernetSwitchTypeNote

    GormEthernetSwitchRepository .down. EthernetSwitchTypeNote
    GormGenericRepository <.up. EthernetSwitchTypeNote
    EthernetSwitch .. EthernetSwitchTypeNote
}

@enduml
