@startuml

!include ../entities/EthernetSwitchPort.puml
!include GormGenericRepository.puml

package infrastructure {
    class GormEthernetSwitchPortRepository

    GormEthernetSwitchPortRepository -down-* GormGenericRepository


    note "EntityType is EthernetSwitchPort \nIDType is uuid.UUID" as EthernetSwitchPortTypeNote

    GormEthernetSwitchPortRepository .down. EthernetSwitchPortTypeNote
    GormGenericRepository <.up. EthernetSwitchPortTypeNote
    EthernetSwitchPort .. EthernetSwitchPortTypeNote
}


@enduml
