@startuml

!include ../entities/HTTPLog.puml
!include GormGenericRepository.puml

package infrastructure {
    class GormHTTPLogRepository

    GormHTTPLogRepository -down-* GormGenericRepository

    note "EntityType is HTTPLog \nIDType is uuid.UUID" as HTTPLogTypeNote

    GormHTTPLogRepository .down. HTTPLogTypeNote
    GormGenericRepository <.up. HTTPLogTypeNote
    HTTPLog .. HTTPLogTypeNote
}

@enduml
