@startuml

!include ../interfaces/IGenericRepository.puml

package infrastructure {
    class GormGenericRepository<IDType, EntityType>

    GormGenericRepository .down.|> IGenericRepository
}

@enduml
