@startuml

!include ../entities/EthernetSwitchVLAN.puml
!include GormGenericRepository.puml

package infrastructure {
    class GormEthernetSwitchVLANRepository

    GormEthernetSwitchVLANRepository -down-* GormGenericRepository


    note "EntityType is EthernetSwitchVLAN \nIDType is uuid.UUID" as EthernetSwitchVLANTypeNote

    GormEthernetSwitchVLANRepository .down. EthernetSwitchVLANTypeNote
    GormGenericRepository <.up. EthernetSwitchVLANTypeNote
    EthernetSwitchVLAN .. EthernetSwitchVLANTypeNote
}

@enduml