@startuml
!include ../entities/DHCP4Config.puml
!include GormGenericRepository.puml

package infrastructure {
    class GormDHCP4ConfigRepository

    GormDHCP4ConfigRepository -down-* GormGenericRepository

    note "EntityType is DHCP4Config \nIDType is uuid.UUID" as DHCP4ConfigTypeNote

    GormDHCP4ConfigRepository .down. DHCP4ConfigTypeNote
    GormGenericRepository <.up. DHCP4ConfigTypeNote
    DHCP4Config .. DHCP4ConfigTypeNote
}

@enduml