@startuml

!include ../entities/HTTPLog.puml
!include GormGenericRepository.puml

package infrastructure {
    class HTTPLogRepository<HTTPLog>

    HTTPLogRepository *-- GormGenericRepository
}

@enduml
