@startuml IEntityModel

package app {
    interface IEntityModel<IDType> {
        +GetID() IDType
        --
        +GetCreatedAt() time.Time
        --
        +GetUpdatedAt() *time.Time
        --
        +GetDeletedAt() *time.Time
    }
}

@enduml
