@startuml IEntityModelDeletedAt

package app {
    interface IEntityModelDeletedAt {
        SetDeleted()
    }
    note bottom of IEntityModelDeletedAt
        Set deletion time
        This method marks that the entity has been deleted
    end note
}

@enduml
