@startuml

package app {
    interface ITFTPServerFactory {
        +Create(config domain.TFTPConfig) (interfaces.ITFTPServer, error)
    }

    note left of ITFTPServerFactory::Create
    Create runtime TFTP server
    end note
}

@enduml