@startuml EthernetSwitchCreateDto
!include EthernetSwitchBaseDto.puml
!include ../../entities/EthernetSwitchModel.puml

class EthernetSwitchCreateDto {
    Password string
}

EthernetSwitchCreateDto *-- EthernetSwitchBaseDto
EthernetSwitchBaseDto::Model -- EthernetSwitchModel
@enduml