@startuml EthernetSwitchBaseDto

package dtos {
    class EthernetSwitchBaseDto {
        Name string
        --
        Serial string
        --
        SwitchModel int
        --
        Address string
        --
        Username string
    }
}

@enduml
