@startuml EthernetSwitchBaseDto

package dtos {
    class EthernetSwitchBaseDto {
        +Name string
        --
        +Serial string
        --
        +SwitchModel string
        --
        +Address string
        --
        +Username string
    }
}

@enduml
