@startuml
!include ../../Entities/EthernetSwitchModel.puml
!include ../../Interfaces/IEntityDtoModel.puml
!include ../BaseDto.puml
!include EthernetSwitchBaseDto.puml

class EthernetSwitchDto {

}
EthernetSwitchDto *-- EthernetSwitchBaseDto
EthernetSwitchDto *-- BaseDto

EthernetSwitchDto <|.. IEntityDtoModel
EthernetSwitchBaseDto::Model -- EthernetSwitchModel

@enduml