@startuml EthernetSwitchUpdateDto

!include EthernetSwitchBaseDto.puml

package dtos {
    class EthernetSwitchUpdateDto {
        +Password string
    }

    EthernetSwitchUpdateDto --* EthernetSwitchBaseDto
}

@enduml
