@startuml EthernetSwitchDto
!include ../../Entities/EthernetSwitchModel.puml
!include ../BaseDto.puml
!include EthernetSwitchBaseDto.puml

class EthernetSwitchDto {

}
EthernetSwitchDto *-- EthernetSwitchBaseDto
EthernetSwitchDto *-- BaseDto

EthernetSwitchBaseDto::Model -- EthernetSwitchModel

@enduml