@startuml EthernetSwitchDto

!include ../BaseDto.puml
!include EthernetSwitchBaseDto.puml

package dtos {
    class EthernetSwitchDto {

    }
    EthernetSwitchDto --* EthernetSwitchBaseDto
    EthernetSwitchDto --* BaseDto  : IDType is uuid.UUID
}

@enduml
