@startuml EthernetSwitchDto
!include ../BaseDto.puml
!include EthernetSwitchBaseDto.puml

class EthernetSwitchDto {

}
EthernetSwitchDto *-- EthernetSwitchBaseDto
EthernetSwitchDto *-- BaseDto

@enduml