@startuml EthernetSwitchCreateDto

!include EthernetSwitchBaseDto.puml

package dtos {
    class EthernetSwitchCreateDto {
        Password string
    }

    EthernetSwitchCreateDto --* EthernetSwitchBaseDto
}

@enduml
