@startuml

package dtos {
    class HostNetworkTrafficRuleBaseDto {
        +Chain string
        --
        +Target string
        --
        +Source string
        --
        +Destination string
    }
}


@enduml