@startuml
!include HostNetworkTrafficRuleBaseDto.puml

package dtos {
    class HostNetworkTrafficRuleCreateDto {
    }

    HostNetworkTrafficRuleCreateDto --* HostNetworkTrafficRuleBaseDto
}
@enduml