@startuml
!include HostNetworkTrafficRuleBaseDto.puml

package dtos {
    class HostNetworkTrafficRuleDeleteDto {
    }

    HostNetworkTrafficRuleDeleteDto --* HostNetworkTrafficRuleBaseDto
}
@enduml