@startuml
!include ../interfaces/IGenericTemplateStorage.puml

package infrastructure {
    class YamlGenericTemplateStorage<TemplateType>

    YamlGenericTemplateStorage .down.|> IGenericTemplateStorage
}
@enduml
