@startuml

!include YamlGenericTemplateStorage.puml
!include ../entities/DeviceTemplate.puml

package infrastructure {
    note "TemplateType is DeviceTemplate" as DeviceTemplateTypeNote

    class YamlDeviceTemplateStorage

    YamlDeviceTemplateStorage --* YamlGenericTemplateStorage
    YamlDeviceTemplateStorage .down. DeviceTemplateTypeNote
    YamlGenericTemplateStorage <.up. DeviceTemplateTypeNote
    DeviceTemplateTypeNote .. DeviceTemplate
}

@enduml
