@startuml

!include ../interfaces/IHostNetworkConfigStorage.puml

package infrastructure {
    class YamlHostNetworkConfigStorage {
        -configFilePath string
    }

    YamlHostNetworkConfigStorage --|> IHostNetworkConfigStorage
}

@enduml