@startuml

package dtos {
    class DHCP4ServerCreateDto {
        +Range string
        --
        +Mask string
        --
        +ServerID string
        --
        +Interface string
        --
        +Gateway string
        --
        +DNS string
        --
        +NTP string
        --
        +Enabled bool
        --
        +Port int
        --
        +LeaseTime int
    }
    note left of DHCP4ServerCreateDto::ServerID
    Server ID DHCP option, IP string.
    end note
}

@enduml