@startuml

!include EthernetSwitchVLANBaseDto.puml
!include ../BaseDto.puml

package dtos {
    class EthernetSwitchVLANDto {
        +VlanID int
        --
        +EthernetSwitchID uuid.UUID
    }

    EthernetSwitchVLANDto --* EthernetSwitchVLANBaseDto
    EthernetSwitchVLANDto --* BaseDto  : IDType is uuid.UUID
}

@enduml
