@startuml HTTPLogDto

!include HostNetworkBridgeBaseDto.puml

package dtos {
    class HostNetworkBridgeDto {
        +Name string
    }
    HostNetworkBridgeDto --* HostNetworkBridgeBaseDto
}

@enduml
