@startuml

!include ../repositories/GormAppLogRepository.puml
!include ../dto/Log/LogDto.puml

package app {
    class AppLogService {
        -repository IGenericRepository[uuid.UUID, domain.AppLog]
        --
        +GetList(ctx context.Context, search string, orderBy string, orderDirection string, page int, pageSize int) (dtos.PaginatedItemsDto[dtos.AppLogDto], error)
        --
        +GetByID(ctx context.Context, id uuid.UUID) (dtos.AppLogDto, error)
    }

    AppLogService .[hidden]up. IGenericRepository

    GormAppLogRepository -right- AppLogService::repository

    note left of AppLogService
        Advanced business logic for Log entity
    end note
}

@enduml
