@startuml

!include ../storages/DeviceTemplateStorage.puml

package app {
    class DeviceTemplateService {
        storage IDeviceTemplateStorage
        --
        GetList(ctx context.Context, search, orderBy, orderDirection string, page, pageSize int) (*dtos.PaginatedListDto[DeviceTemplateDto], error)
        --
        GetByName(ctx context.Context, name string) (*DeviceTemplateDto, error)
        --
    }
    DeviceTemplateService::storage -- DeviceTemplateStorage
}

@enduml
