@startuml

!include ../storages/YamlDeviceTemplateStorage.puml
!include ../dto/DeviceTemplate/DeviceTemplateDto.puml

package app {
    class DeviceTemplateService {
        -storage IGenericTemplateStorage<DeviceTemplate>
        --
        +GetList(ctx context.Context, search, orderBy, orderDirection string, page, pageSize int) (dtos.PaginatedItemsDto[dtos.DeviceTemplateDto], error)
        --
        +GetByName(ctx context.Context, name string) (dtos.DeviceTemplateDto, error)
    }
    DeviceTemplateService::storage -- YamlDeviceTemplateStorage
}

@enduml
