@startuml
!include GenericService.puml
!include ../repositories/EthernetSwitchRepository.puml
!include ../dto/EthernetSwitch/EthernetSwitchCreateDto.puml
!include ../dto/EthernetSwitch/EthernetSwitchUpdateDto.puml
!include ../dto/EthernetSwitch/EthernetSwitchDto.puml

package app {
    class EthernetSwitchService {
        repository IGenericRepository<EthernetSwitch>
        --
    }

    note left of EthernetSwitchService
        Advanced business logic for EthernetSwitch entity
        For example:
        DTO Validation
        Checking the uniqueness of serial numbers
    end note

    EthernetSwitchRepository -right- EthernetSwitchService::repository
    GenericService -up-* EthernetSwitchService

    EthernetSwitchService .[hidden]up. IGenericRepository

    note as EthernetSwitchServiceTypes
    EntityType is EthernetSwitch
    CreateDtoType is EthernetSwitchCreateDto
    UpdateDtoType is EthernetSwitchUpdateDto
    DtoType is EthernetSwitchDto
    end note

    EthernetSwitchService .down. EthernetSwitchServiceTypes
    GenericService <.up. EthernetSwitchServiceTypes

    EthernetSwitchServiceTypes .. EthernetSwitchCreateDto
    EthernetSwitchServiceTypes .. EthernetSwitchUpdateDto
    EthernetSwitchServiceTypes .. EthernetSwitchDto

}
@enduml
