@startuml
!include GenericService.puml
!include ../repositories/EthernetSwitchRepository.puml
!include ../dto/EthernetSwitch/EthernetSwitchCreateDto.puml
!include ../dto/EthernetSwitch/EthernetSwitchUpdateDto.puml
!include ../dto/EthernetSwitch/EthernetSwitchDto.puml

package app {
    class EthernetSwitchService<EthernetSwitch, EthernetSwitchCreateDto, EthernetSwitchUpdateDto, EthernetSwitchDto> {
        repository IGenericRepository
        --
    }
    note top of EthernetSwitchService
        Advanced business logic for EthernetSwitch entity
        For example:
        DTO Validation
        Checking the uniqueness of serial numbers
    end note

    EthernetSwitchService::repository -- EthernetSwitchRepository
    EthernetSwitchService *-- GenericService

    IGenericRepository -[hidden]up- IEntityModelDeletedAt
}
@enduml
