@startuml
!include GenericService.puml
!include ../repositories/EthernetSwitchPortRepository.puml
!include ../dto/EthernetSwitchPort/EthernetSwitchPortCreateDto.puml
!include ../dto/EthernetSwitchPort/EthernetSwitchPortUpdateDto.puml
!include ../dto/EthernetSwitchPort/EthernetSwitchPortDto.puml

package app {
    class EthernetSwitchPortService {
        -repository IGenericRepository<EthernetSwitchPort>
        --
        -switchRepository IGenericRepository<EthernetSwitch>
        --
        +GetPortByID(ctx context.Context, switchID, id uuid.UUID) (*dtos.EthernetSwitchPortDto, error)
        --
        +CreatePort(ctx context.Context, switchID uuid.UUID, createDto dtos.EthernetSwitchPortCreateDto) (uuid.UUID, error)
        --
        +UpdatePort(ctx context.Context, switchID, id uuid.UUID, updateDto dtos.EthernetSwitchPortUpdateDto) error
        --
        +GetPorts(ctx context.Context, switchID uuid.UUID, search, orderBy, orderDirection string, page, pageSize int) (*dtos.PaginatedListDto[dtos.EthernetSwitchPortDto], error)
        --
        +DeletePort(ctx context.Context, switchID, id uuid.UUID) error
    }

    note left of EthernetSwitchPortService::switchRepository
        Used to check the existence of switches
    end note

    note left of EthernetSwitchPortService
        Advanced business logic for EthernetSwitchPort entity
        For example:
        DTO Validation
        Checking the uniqueness of port names
        Checking the existence of a switch
    end note

    EthernetSwitchPortRepository -right- EthernetSwitchPortService::repository
    GenericService -up-* EthernetSwitchPortService

    EthernetSwitchPortService .[hidden]up. IGenericRepository

    note as EthernetSwitchPortServiceTypes
    EntityType is EthernetSwitchPort
    CreateDtoType is EthernetSwitchPortCreateDto
    UpdateDtoType is EthernetSwitchPortUpdateDto
    DtoType is EthernetSwitchPortDto
    end note

    EthernetSwitchPortService .down. EthernetSwitchPortServiceTypes
    GenericService <.up. EthernetSwitchPortServiceTypes

    EthernetSwitchPortServiceTypes .. EthernetSwitchPortCreateDto
    EthernetSwitchPortServiceTypes .. EthernetSwitchPortUpdateDto
    EthernetSwitchPortServiceTypes .. EthernetSwitchPortDto
}
@enduml
