@startuml
!include ../interfaces/generic/IGenericService.puml

class GenericService<EntityType, CreateDtoType, UpdateDtoType, DtoType> {
    repository IGenericRepository
    --
    logger *logrus.Logger
    --
    logSourceName string
}

GenericService <|.. IGenericService
@enduml