@startuml
!include ../interfaces/IGenericService.puml

package app {
    class GenericService<EntityType, CreateDtoType, UpdateDtoType, DtoType> {
        repository IGenericRepository
        --
        logger *logrus.Logger
        --
        logSourceName string
    }
    GenericService .down.|> IGenericService
}

@enduml
