@startuml

!include ../dto/HostNetworkVlan/HostNetworkVlanDto.puml
!include ../dto/HostNetworkVlan/HostNetworkVlanCreateDto.puml
!include ../dto/HostNetworkVlan/HostNetworkVlanUpdateDto.puml
!include ../dto/HostNetworkBridge/HostNetworkBridgeDto.puml
!include ../dto/HostNetworkBridge/HostNetworkBridgeCreateDto.puml
!include ../dto/HostNetworkBridge/HostNetworkBridgeUpdateDto.puml
!include ../dto/HostNetworkTrafficRule/HostNetworkTrafficRuleDto.puml
!include ../dto/HostNetworkTrafficRule/HostNetworkTrafficRuleCreateDto.puml
!include ../dto/HostNetworkTrafficRule/HostNetworkTrafficRuleDeleteDto.puml

!include ../managers/HostNetworkManager.puml

package app {
    class HostNetworkService {
        -manager IHostNetworkManager
        --
        +GetVlanList() ([]HostNetworkVlanDto, error)
        --
        +GetVlanByName(name string) (HostNetworkVlanDto, error)
        --
        +CreateVlan(createDto HostNetworkVlanCreateDto) (HostNetworkVlanDto, error)
        --
        +UpdateVlan(name string, updateDto HostNetworkVlanUpdateDto) (HostNetworkVlanDto, error)
        --
        +DeleteVlan(name string) error
        --
        +GetBridgeList() ([]HostNetworkBridgeDto, error)
        --
        +GetBridgeByName(name string) (dtos.HostNetworkBridgeDto, error)
        --
        +CreateBridge(createDto dtos.HostNetworkBridgeCreateDto) (dtos.HostNetworkBridgeDto, error)
        --
        +UpdateBridge(bridgeName string, updateDto dtos.HostNetworkBridgeUpdateDto) (dtos.HostNetworkBridgeDto, error)
        --
        +DeleteBridge(bridgeName string) error
        --
        +CreateTrafficRule(table string, ruleDto dtos.HostNetworkTrafficRuleCreateDto) (dtos.HostNetworkTrafficRuleDto, error)
        --
        +DeleteTrafficRule(table string, ruleDto dtos.HostNetworkTrafficRuleDeleteDto) error
        --
        +GetChainRules(table string, chain string) ([]dtos.HostNetworkTrafficRuleDto, error)
        --
        +GetTableRules(table string) ([]dtos.HostNetworkTrafficRuleDto, error)
    }
    HostNetworkService::manager -- HostNetworkManager

    note right of HostNetworkService::GetVlanList
        Get list of VLAN interfaces on the host
    end note

    note right of HostNetworkService::GetVlanByName
        Get VLAN interface by Name
    end note

    note right of HostNetworkService::CreateVlan
        Create new VLAN interface on the host
    end note

    note right of HostNetworkService::UpdateVlan
        Update VLAN interface on the host
    end note

    note right of HostNetworkService::DeleteVlan
        Delete VLAN interface from host
    end note

    note right of HostNetworkService::GetBridgeList
        Get list of bridge interfaces on the host
    end note

    note right of HostNetworkService::GetBridgeByName
        Get bridge interface by Name
    end note

    note right of HostNetworkService::CreateBridge
        Create new bridge interface on the host
    end note

    note right of HostNetworkService::UpdateBridge
        Update bridge interface on the host
    end note

    note right of HostNetworkService::DeleteBridge
        Delete bridge interface from host
    end note

    note right of HostNetworkService::CreateTrafficRule
        Create netfilter traffic rule for specified table
    end note

    note right of HostNetworkService::DeleteTrafficRule
        Delete netfilter traffic rule in specified table
    end note

    note right of HostNetworkService::GetChainRules
        Get selected netfilter chain rules at specified table
    end note

    note right of HostNetworkService::GetTableRules
        Get specified netfilter table rules
    end note
}

@enduml
