@startuml

!include GenericService.puml
!include ../repositories/HTTPLogRepository.puml
!include ../dto/HTTPLog/HTTPLogDto.puml

package app {
    class HTTPLogService {
        repository IGenericRepository<HTTPLog>
    }

    HTTPLogService .[hidden]up. IGenericRepository

    HTTPLogRepository -right- HTTPLogService::repository
    GenericService *-up- HTTPLogService

    note left of HTTPLogService
        Advanced business logic for HTTPLog entity
    end note

    note as HTTPLogServiceTypes
        EntityType is HTTPLog
        CreateDtoType is HTTPLogDto
        UpdateDtoType is HTTPLogDto
        DtoType is HTTPLogDto
        Because the service is read-only
    end note

    HTTPLogService .down. HTTPLogServiceTypes
    GenericService <.up. HTTPLogServiceTypes

    HTTPLogServiceTypes .. HTTPLogDto
}

@enduml
