@startuml

!include GenericService.puml
!include ../repositories/HTTPLogRepository.puml
!include ../dto/HTTPLog/HTTPLogDto.puml

package app {
    class HTTPLogService<HTTPLog,HTTPLogDto,HTTPLogDto,HTTPLogDto> {
        repository IGenericRepository
    }

    HTTPLogService *-- GenericService
    HTTPLogService::repository -- HTTPLogRepository
}

@enduml
