@startuml

!include ../repositories/HTTPLogRepository.puml
!include ../dto/HTTPLog/HTTPLogDto.puml

package app {
    class HTTPLogService {
        -repository IGenericRepository<HTTPLog>
        --
        +GetList(ctx context.Context, search string, orderBy string, orderDirection string, page int, pageSize int) (dtos.PaginatedItemsDto[dtos.HTTPLogDto], error)
        --
        +GetByID(ctx context.Context, id uuid.UUID) (dtos.HTTPLogDto, error)
    }

    HTTPLogService .[hidden]up. IGenericRepository

    HTTPLogRepository -right- HTTPLogService::repository

    note left of HTTPLogService
        Advanced business logic for HTTPLog entity
    end note
}

@enduml
