@startuml

!include ../repositories/LogRepository.puml
!include ../dto/Log/LogDto.puml

package app {
    class LogService {
        -repository IGenericRepository
        --
        +GetList(ctx context.Context, search string, orderBy string, orderDirection string, page int, pageSize int) (dtos.PaginatedItemsDto[dtos.AppLogDto], error)
        --
        +GetByID(ctx context.Context, id uuid.UUID) (dtos.AppLogDto, error)
    }

    LogService .[hidden]up. IGenericRepository

    LogRepository -right- LogService::repository

    note left of LogService
        Advanced business logic for Log entity
    end note
}

@enduml
