@startuml

!include GenericService.puml
!include ../repositories/LogRepository.puml
!include ../dto/Log/LogDto.puml
!include ../entities/Log.puml

package app {
    class LogService<Log, LogDto, LogDto, LogDto> {
        repository IGenericRepository
        --
    }

    LogService *-- GenericService
    LogService::repository -- LogRepository
}

@enduml
