@startuml EthernetSwitchPortDto

!include EthernetSwitchPortBaseDto.puml
!include ../BaseDto.puml

package dtos {
    class EthernetSwitchPortDto

    EthernetSwitchPortDto --* BaseDto  : IDType is uuid.UUID
    EthernetSwitchPortDto --* EthernetSwitchPortBaseDto
}

@enduml
