@startuml
!include ../../Entities/EthernetSwitchPoePortType.puml
class EthernetSwitchPortUpdateDto {
    PoeType EthernetSwitchPoePortType
    --
    Name string
}
EthernetSwitchPortUpdateDto::PoeType -- EthernetSwitchPoePortType
@enduml