@startuml EthernetSwitchPortCreateDto

!include EthernetSwitchPortBaseDto.puml

package dtos {
    class EthernetSwitchPortCreateDto

    EthernetSwitchPortCreateDto --* EthernetSwitchPortBaseDto
}

@enduml
