@startuml EthernetSwitchPortUpdateDto

!include EthernetSwitchPortBaseDto.puml

package dtos {
    class EthernetSwitchPortUpdateDto

    EthernetSwitchPortUpdateDto --* EthernetSwitchPortBaseDto
}

@enduml
