@startuml EthernetSwitchPortBaseDto

package dtos {
    class EthernetSwitchPortBaseDto {
        EthernetSwitchID uuid.UUID
        --
        POEType string
        --
        Name string
    }
}

@enduml
