@startuml EthernetSwitchPortDto

!include EthernetSwitchPortBaseDto.puml
!include ../BaseDto.puml
class EthernetSwitchPortDto {

}

EthernetSwitchPortDto --* BaseDto
EthernetSwitchPortDto --* EthernetSwitchPortBaseDto
@enduml
