@startuml EthernetSwitchPortBaseDto

package dtos {
    class EthernetSwitchPortBaseDto {
        +POEType string
        --
        +Name string
        --
        +POEEnabled bool
        --
        +PVID int
    }
}

@enduml
