@startuml
!include ../services/EthernetSwitchService.puml

package controllers {
    class EthernetSwitchGinController {
        -service interfaces.IGenericService[EthernetSwitchDto, EthernetSwitchCreateDto, EthernetSwitchUpdateDto, EthernetSwitch]
        --
        +GetList(ctx *gin.Context)
        --
        +GetByID(ctx *gin.Context)
        --
        +Create(ctx *gin.Context)
        --
        +Update(ctx *gin.Context)
        --
        +Delete(ctx *gin.Context)
        --
        +GetSupportedModels(ctx *gin.Context)
    }

    note left of EthernetSwitchGinController::GetSupportedModels
    Get supported switch models
    end note

    EthernetSwitchGinController .up. EthernetSwitchServiceTypes
    EthernetSwitchService -left- EthernetSwitchGinController::service

}

@enduml
