@startuml
!include ../interfaces/IGenericService.puml

package controllers {
    class GinGenericController<DtoType, CreateDtoType, UpdateDtoType, EntityType> {
        -service interfaces.IGenericService[DtoType, CreateDtoType, UpdateDtoType, EntityType]
        --
        -logger *logrus.Logger
        --
        +GetList(ctx *gin.Context)
        --
        +GetByID(ctx *gin.Context)
        --
        +Create(ctx *gin.Context)
        --
        +Update(ctx *gin.Context)
        --
        +Delete(ctx *gin.Context)
    }

    note left of GinGenericController::GetList
    Get list of elements with search and pagination
    end note

    note left of GinGenericController::GetByID
    Get entity by id
    end note

    note left of GinGenericController::Create(
    Create new entity
    end note

    note left of GinGenericController::Update(
    Update entity by id
    end note

    note left of GinGenericController::Delete
    Soft deleting entity
    end note

    IGenericService .left. GinGenericController::service
}

@enduml
