@startuml
boundary    HttpServer  as httpServer
control     Service     as service
entity      Repository  as repository
collections ORM        as orm
database    db          as DB
httpServer <-> service : DTO\n(data transfer objects).
service <-> repository : Entities structures.
repository <-> orm : Entities structures.
orm <- DB : db tables
@enduml