@startuml

!include Entity.puml

package domain {
    class AppLog {
        +ActionID uuid.UUID `gorm:"index"`
        --
        +Level string
        --
        +Source string
        --
        +Message string
    }
    AppLog -down-* EntityUUID
}

@enduml
