@startuml

package domain {
    enum DHCPServerState {
            DHCPStateLaunched
            --
            DHCPStateStopped
            --
            DHCPStateError
            --
            DHCPStateNone
            --
            +ToString()
    }
}

@enduml