@startuml Entity

!include ../interfaces/IEntityModel.puml
!include ../interfaces/IEntityModelDeletedAt.puml

package domain {
    class Entity {
        ID uuid.UUID `gorm:"primarykey"`
        --
        CreatedAt time.Time `gorm:"index"`
        --
        UpdatedAt time.Time `gorm:"index"`
        --
        DeletedAt time.Time `gorm:"index"`
    }
    Entity <|.. IEntityModelDeletedAt
    Entity <|.. IEntityModel

    IEntityModelDeletedAt .right[hidden]. IEntityModel
}

@enduml
