@startuml Entity

!include ../interfaces/IEntityModel.puml

package domain {
    class EntityUUID {
    }
    EntityUUID --* Entity : IDType is uuid.UUID
    class Entity<IDType> {
        +ID IDType
        --
        +CreatedAt time.Time
        --
        +UpdatedAt *time.Time
        --
        +DeletedAt gorm.DeletedAt
    }
    Entity .down.|> IEntityModel
}

@enduml
