@startuml

!include Entity.puml

package domain {
    class EthernetSwitch {
        +Name string
        --
        +Serial string
        --
        +SwitchModel string
        --
        +Address string
        --
        +Username string
        --
        +Password string
    }
    note left of EthernetSwitch::Serial
    Unique
    end note

    note left of EthernetSwitch::Address
    Unique
    Ip address of the switch
    end note

    EthernetSwitch -down-* EntityUUID
}

@enduml
