@startuml EthernetSwitchPort

!include Entity.puml

package domain {
    class EthernetSwitchPort {
        EthernetSwitchId uuid.UUID
        --
        POEType string
        --
        Name string
    }

    EthernetSwitchPort -down-* Entity

    note left of EthernetSwitchPort::POEType
      POE port type
      can be: "poe", "poe+", "passive24", "none"
    end note

    note left of EthernetSwitchPort::Name
      Unique within 1 switch
    end note
}

@enduml
