@startuml EthernetSwitchPort
!include Entity.puml
!include EthernetSwitchPoePortType.puml
!include EthernetSwitch.puml


class EthernetSwitchPort {
    EthernetSwitchId uuid.UUID
    --
    PoeType EthernetSwitchPoePortType
    --
    Name string
}

EthernetSwitchPort *-- Entity
EthernetSwitchPort::PoeType -- EthernetSwitchPoePortType
EthernetSwitchPort::EthernetSwitchId -- EthernetSwitch

note left of EthernetSwitchPort::Name
  Unique within 1 switch
end note

@enduml