@startuml EthernetSwitchPort

!include Entity.puml
!include EthernetSwitchPoePortType.puml

package domain {
    class EthernetSwitchPort {
        EthernetSwitchId uuid.UUID
        --
        PoeType EthernetSwitchPoePortType
        --
        Name string
    }

    EthernetSwitchPort::PoeType -- EthernetSwitchPoePortType
    EthernetSwitchPort -down-* Entity
    note left of EthernetSwitchPort::Name
      Unique within 1 switch
    end note
}

@enduml
