@startuml

!include Entity.puml
!include EthernetSwitchModel.puml

package domain {
    class EthernetSwitch {
        Name string
        --
        Serial string
        --
        SwitchModel EthernetSwitchModel
        --
        Address string
        --
        Username string
        --
        Password string
    }
    note left of EthernetSwitch::Serial
    Unique
    end note

    note left of EthernetSwitch::Address
    Ip address of the switch
    end note

    EthernetSwitch -down-* Entity
    EthernetSwitch::SwitchModel -right- EthernetSwitchModel
}

@enduml
