@startuml

!include HostNetworkDevice.puml
!include HostNetworkVlan.puml

package domain {
    class HostNetworkConfig {
        +Devices []HostNetworkDevice
        --
        +Vlans   []HostNetworkVlan
    }

    HostNetworkConfig::Devices -- HostNetworkDevice
    HostNetworkConfig::Vlans -- HostNetworkVlan
}

@enduml
