@startuml Project

package domain {
    class HostNetworkTrafficRule {
        Chain string
        --
        Target string
        --
        Source string
        --
        Destination string
    }
}

@enduml
