@startuml

!include ../interfaces/IHostNetworkLink.puml

package domain {
    class HostNetworkLink {
        +Name string
        --
        +Addresses []net.IPNet
        --
        +Type string
    }
    note left of HostNetworkLink::Name
    Unique name of the network interface
    end note

    note left of HostNetworkLink::Type
    Default value is "none"
    because HostNetworkLink is a basic class
    end note

    HostNetworkLink --|> IHostNetworkLink
}

@enduml
