@startuml EthernetSwitch

!include Entity.puml

package domain {
    class HTTPLog {
        HTTPMethod string
        --
        Domain string
        --
        RelativePath string `gorm:"index"`
        --
        QueryParams string
        --
        QueryParamsInd string `gorm:"index"`
        --
        ClientIP string `gorm:"index"`
        --
        Latency int
        --
        RequestBody string
        --
        ResponseBody string
        --
        RequestHeaders string
        --
        ResponseHeaders string
        --
        CustomRequestHeaders string
        --
        CustomRequestHeadersInd string `gorm:"index"`
    }
    HTTPLog *-- Entity
}

@enduml
