@startuml

!include Entity.puml

package domain {
    class Log {
        ActionID uuid.UUID `gorm:"index"`
        --
        Level string
        --
        Source string
        --
        Message string
    }
    Log -down-* Entity
}

@enduml
