@startuml

package domain {
    enum TFTPServerState {
            TFTPStateLaunched
            --
            TFTPStateStopped
            --
            TFTPStateError
            --
            TFTPStateNone
            --
            +ToString()
    }
}

@enduml